@startchen
!theme mars
'!theme mono

'vertical spacing
skinparam ranksep 30
'horizontal spacing
skinparam nodesep 10  

'entity definitions
entity Game {
        'pk
        gm_id <<key>>
        name
        genre <<multi>>
        'fk
        developer
        'fk
        publisher
}

entity Series <<weak>> {
        name
        games <<multi>>
}

entity Genre {
        'pk
        gn_id <<key>>
        name
}

entity Console {
        'pk
        name <<key>>
        console_developer
        rel_yr
        eol_yr
}

entity Company{
        'pk
        name <<key>>
        founding_yr
        parent_company
        '... IDK what else to put here
}

entity Emulator {
        'pk
        name <<key>>
        emulated_console
        init_rel
        license
        current_rel_ver
        website
}
'relationship definitions
relationship "Game_Genre" as gg {
}
relationship "Made_of" as MO <<identifying>> {
}
relationship "Makes_Game" as mg {
}
relationship "Publishes_Game" as pg {
}
relationship "Makes_Console" as mc {
}
relationship "Playable_On_Console" as ploc {
}
relationship "Playable_On_Emulator" as ploe {
}
relationship Emulates {
}

Game -(1,N)- MO
MO =1= Series

Game -N- gg
gg -N- Genre

Game =N= ploc
ploc -N- Console

Game -N- ploe
ploe -1- Emulator

mg -1- Company
mg =N= Game

pg -1- Company
pg -N- Game

mc -1- Company
mc =N= Console

Emulates -1- Console
Emulates =1= Emulator
@endchen
